<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActivityTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $now = date('Y-m-d H:i:s');

        $activities = [
            ["code" => 41, "category" => "Comm", "name" => "Advertising", "created_at" => $now, "updated_at" => $now],
            ["code" => 161, "category" => "Comm", "name" => "Aircraft & train spare parts trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 159, "category" => "Comm", "name" => "Amusement Equipment & supplies trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 144, "category" => "Comm", "name" => "Animal skin trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 90, "category" => "Comm", "name" => "Art production", "created_at" => $now, "updated_at" => $now],
            ["code" => 51, "category" => "Comm", "name" => "Auto spare parts trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 221, "category" => "Comm", "name" => "Bags, packaging materials & paper trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 209, "category" => "Comm", "name" => "banks, finance & credit group", "created_at" => $now, "updated_at" => $now],
            ["code" => 204, "category" => "Comm", "name" => "beauty & baby care requisites", "created_at" => $now, "updated_at" => $now],
            ["code" => 109, "category" => "Comm", "name" => "Broadcasting and communications", "created_at" => $now, "updated_at" => $now],
            ["code" => 95, "category" => "Comm", "name" => "Building maintenance, surveillance and cleaning services", "created_at" => $now, "updated_at" => $now],
            ["code" => 68, "category" => "Comm", "name" => "Building materials trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 49, "category" => "Comm", "name" => "Car rent and passenger transport", "created_at" => $now, "updated_at" => $now],
            ["code" => 69, "category" => "Comm", "name" => "Chemicals trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 91, "category" => "Comm", "name" => "Cinema & theaters", "created_at" => $now, "updated_at" => $now],
            ["code" => 154, "category" => "Comm", "name" => "Cleaning equipment trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 137, "category" => "Comm", "name" => "Commercial brokerage", "created_at" => $now, "updated_at" => $now],
            ["code" => 230, "category" => "Comm", "name" => "Consumer Stores Group", "created_at" => $now, "updated_at" => $now],
            ["code" => 8, "category" => "Comm", "name" => "Contracting and building works", "created_at" => $now, "updated_at" => $now],
            ["code" => 163, "category" => "Comm", "name" => "Cooperation Societies", "created_at" => $now, "updated_at" => $now],
            ["code" => 158, "category" => "Comm", "name" => "Domestic gas distribution", "created_at" => $now, "updated_at" => $now],
            ["code" => 61, "category" => "Comm", "name" => "Electrical trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 59, "category" => "Comm", "name" => "Electronics group", "created_at" => $now, "updated_at" => $now],
            ["code" => 76, "category" => "Comm", "name" => "exchange and financial services", "created_at" => $now, "updated_at" => $now],
            ["code" => 89, "category" => "Comm", "name" => "Facility management", "created_at" => $now, "updated_at" => $now],
            ["code" => 134, "category" => "Comm", "name" => "Filling station", "created_at" => $now, "updated_at" => $now],
            ["code" => 146, "category" => "Comm", "name" => "Fish trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 78, "category" => "Comm", "name" => "Floor mills", "created_at" => $now, "updated_at" => $now],
            ["code" => 79, "category" => "Comm", "name" => "Flowers and plants", "created_at" => $now, "updated_at" => $now],
            ["code" => 145, "category" => "Comm", "name" => "Fodders & animal food trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 162, "category" => "Comm", "name" => "Foodstuff supply", "created_at" => $now, "updated_at" => $now],
            ["code" => 53, "category" => "Comm", "name" => "Foodstuff trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 66, "category" => "Comm", "name" => "Fuel and petroleum products trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 135, "category" => "Comm", "name" => "Fuel supply", "created_at" => $now, "updated_at" => $now],
            ["code" => 62, "category" => "Comm", "name" => "Furniture trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 60, "category" => "Comm", "name" => "Home appliances trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 96, "category" => "Comm", "name" => "Insurance", "created_at" => $now, "updated_at" => $now],
            ["code" => 97, "category" => "Comm", "name" => "Investment", "created_at" => $now, "updated_at" => $now],
            ["code" => 63, "category" => "Comm", "name" => "Jewellery trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 206, "category" => "Comm", "name" => "leather trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 142, "category" => "Comm", "name" => "Livestock trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 98, "category" => "Comm", "name" => "Machinery and equipment rental", "created_at" => $now, "updated_at" => $now],
            ["code" => 155, "category" => "Comm", "name" => "Mechanical & engineering equipment trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 149, "category" => "Comm", "name" => "Medical eye glasses trading & eyes testing services", "created_at" => $now, "updated_at" => $now],
            ["code" => 56, "category" => "Comm", "name" => "Medicines trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 67, "category" => "Comm", "name" => "Metals & its products trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 167, "category" => "Comm", "name" => "Office & electronic equipment rental", "created_at" => $now, "updated_at" => $now],
            ["code" => 140, "category" => "Comm", "name" => "Other Personal & trading services", "created_at" => $now, "updated_at" => $now],
            ["code" => 225, "category" => "Comm", "name" => "Other Rental Services", "created_at" => $now, "updated_at" => $now],
            ["code" => 280, "category" => "Comm", "name" => "Other Trading Activities", "created_at" => $now, "updated_at" => $now],
            ["code" => 52, "category" => "Comm", "name" => "Packing services", "created_at" => $now, "updated_at" => $now],
            ["code" => 55, "category" => "Comm", "name" => "Perfumery", "created_at" => $now, "updated_at" => $now],
            ["code" => 102, "category" => "Comm", "name" => "Pets nursery and trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 108, "category" => "Comm", "name" => "Postal services", "created_at" => $now, "updated_at" => $now],
            ["code" => 143, "category" => "Comm", "name" => "Poultry trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 54, "category" => "Comm", "name" => "Ready made garments group", "created_at" => $now, "updated_at" => $now],
            ["code" => 77, "category" => "Comm", "name" => "Real estate", "created_at" => $now, "updated_at" => $now],
            ["code" => 70, "category" => "Comm", "name" => "Roastry", "created_at" => $now, "updated_at" => $now],
            ["code" => 200, "category" => "Comm", "name" => "Separate trading activities", "created_at" => $now, "updated_at" => $now],
            ["code" => 160, "category" => "Comm", "name" => "Ships & boats trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 220, "category" => "Comm", "name" => "sport equipment rental", "created_at" => $now, "updated_at" => $now],
            ["code" => 64, "category" => "Comm", "name" => "Sports equipment trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 57, "category" => "Comm", "name" => "Stationary and books trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 156, "category" => "Comm", "name" => "Supermarket", "created_at" => $now, "updated_at" => $now],
            ["code" => 205, "category" => "Comm", "name" => "tents & tarpaulin trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 171, "category" => "Comm", "name" => "Time sharing", "created_at" => $now, "updated_at" => $now],
            ["code" => 65, "category" => "Comm", "name" => "Tobacco and smoking accessories trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 50, "category" => "Comm", "name" => "Trading in motor vehicles and motorcycles", "created_at" => $now, "updated_at" => $now],
            ["code" => 48, "category" => "Comm", "name" => "Transport, shipping and storage", "created_at" => $now, "updated_at" => $now],
            ["code" => 235, "category" => "Comm", "name" => "Used Articles Trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 157, "category" => "Comm", "name" => "Used auto spare parts trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 164, "category" => "Comm", "name" => "Used electronics & furniture trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 165, "category" => "Comm", "name" => "Used heavy equipment trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 207, "category" => "Comm", "name" => "vending machines trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 148, "category" => "Comm", "name" => "Veterinary equipment trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 58, "category" => "Comm", "name" => "Video and recordings", "created_at" => $now, "updated_at" => $now],
            ["code" => 150, "category" => "Comm", "name" => "Waste trading", "created_at" => $now, "updated_at" => $now],
            ["code" => 28, "category" => "Indl", "name" => "Appliances and machinery manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 25, "category" => "Indl", "name" => "Block and building stones industry", "created_at" => $now, "updated_at" => $now],
            ["code" => 73, "category" => "Indl", "name" => "Bread manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 114, "category" => "Indl", "name" => "Carpet & mat manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 107, "category" => "Indl", "name" => "Casting of steel and iron", "created_at" => $now, "updated_at" => $now],
            ["code" => 305, "category" => "Indl", "name" => "Charcoal Production", "created_at" => $now, "updated_at" => $now],
            ["code" => 127, "category" => "Indl", "name" => "Coating, insulation, seals & protection materials manufacture", "created_at" => $now, "updated_at" => $now],
            ["code" => 115, "category" => "Indl", "name" => "Cotton & metal nets & ropes manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 27, "category" => "Indl", "name" => "Equipment and engines manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 119, "category" => "Indl", "name" => "Fish canning & freezing", "created_at" => $now, "updated_at" => $now],
            ["code" => 11, "category" => "Indl", "name" => "Fodder and fertilizers manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 72, "category" => "Indl", "name" => "Food industries", "created_at" => $now, "updated_at" => $now],
            ["code" => 10, "category" => "Indl", "name" => "Foodstuff mills and packaging", "created_at" => $now, "updated_at" => $now],
            ["code" => 116, "category" => "Indl", "name" => "Glass & chinaware manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 24, "category" => "Indl", "name" => "Glass industries", "created_at" => $now, "updated_at" => $now],
            ["code" => 128, "category" => "Indl", "name" => "Goldsmith & gold repairing", "created_at" => $now, "updated_at" => $now],
            ["code" => 170, "category" => "Indl", "name" => "Lenses cutting & glass repairing", "created_at" => $now, "updated_at" => $now],
            ["code" => 125, "category" => "Indl", "name" => "Light aircraft manufacturing & maintenance", "created_at" => $now, "updated_at" => $now],
            ["code" => 30, "category" => "Indl", "name" => "Lighting equipment manufacturing1", "created_at" => $now, "updated_at" => $now],
            ["code" => 31, "category" => "Indl", "name" => "Manufacture of batteries", "created_at" => $now, "updated_at" => $now],
            ["code" => 32, "category" => "Indl", "name" => "Manufacture of eyeglasses", "created_at" => $now, "updated_at" => $now],
            ["code" => 33, "category" => "Indl", "name" => "Manufacture of gold and precious stones cutting", "created_at" => $now, "updated_at" => $now],
            ["code" => 34, "category" => "Indl", "name" => "Manufacture of mats and rugs", "created_at" => $now, "updated_at" => $now],
            ["code" => 21, "category" => "Indl", "name" => "Manufacture of medicines", "created_at" => $now, "updated_at" => $now],
            ["code" => 35, "category" => "Indl", "name" => "Manufacture of motor vehicles, motorcycles & its spare parts", "created_at" => $now, "updated_at" => $now],
            ["code" => 19, "category" => "Indl", "name" => "Manufacture of petroleum products", "created_at" => $now, "updated_at" => $now],
            ["code" => 22, "category" => "Indl", "name" => "Manufacture of tyres and rubber products", "created_at" => $now, "updated_at" => $now],
            ["code" => 15, "category" => "Indl", "name" => "Manufacturing of bags, shoes and leather products", "created_at" => $now, "updated_at" => $now],
            ["code" => 20, "category" => "Indl", "name" => "Manufacturing of chemicals", "created_at" => $now, "updated_at" => $now],
            ["code" => 14, "category" => "Indl", "name" => "Manufacturing of garments and rugs", "created_at" => $now, "updated_at" => $now],
            ["code" => 17, "category" => "Indl", "name" => "Manufacturing of paper and paper products", "created_at" => $now, "updated_at" => $now],
            ["code" => 13, "category" => "Indl", "name" => "Manufacturing of tobacco and cigarettes", "created_at" => $now, "updated_at" => $now],
            ["code" => 16, "category" => "Indl", "name" => "Manufacturing of wood, wood products and Furniture", "created_at" => $now, "updated_at" => $now],
            ["code" => 7, "category" => "Indl", "name" => "Meat processing", "created_at" => $now, "updated_at" => $now],
            ["code" => 122, "category" => "Indl", "name" => "Metal containers & boxes manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 104, "category" => "Indl", "name" => "Metal home appliances manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 120, "category" => "Indl", "name" => "Other metal industries", "created_at" => $now, "updated_at" => $now],
            ["code" => 131, "category" => "Indl", "name" => "Oven & stove manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 106, "category" => "Indl", "name" => "Paper home appliances manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 26, "category" => "Indl", "name" => "Personal requisites manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 71, "category" => "Indl", "name" => "Petroleum and metal extraction", "created_at" => $now, "updated_at" => $now],
            ["code" => 29, "category" => "Indl", "name" => "Pipes and wires manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 105, "category" => "Indl", "name" => "Plastic home appliances manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 23, "category" => "Indl", "name" => "Plastic industries", "created_at" => $now, "updated_at" => $now],
            ["code" => 43, "category" => "Indl", "name" => "Power generation and transmission", "created_at" => $now, "updated_at" => $now],
            ["code" => 201, "category" => "Indl", "name" => "Separate industrial activities", "created_at" => $now, "updated_at" => $now],
            ["code" => 40, "category" => "Indl", "name" => "Ship building and repairing", "created_at" => $now, "updated_at" => $now],
            ["code" => 126, "category" => "Indl", "name" => "Stationary manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 118, "category" => "Indl", "name" => "steel tool manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 121, "category" => "Indl", "name" => "Steel workshop", "created_at" => $now, "updated_at" => $now],
            ["code" => 103, "category" => "Indl", "name" => "Structural steel manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 113, "category" => "Indl", "name" => "Textiles & products manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 36, "category" => "Indl", "name" => "Waste collection and treatment", "created_at" => $now, "updated_at" => $now],
            ["code" => 12, "category" => "Indl", "name" => "water manufacturing and bottling", "created_at" => $now, "updated_at" => $now],
            ["code" => 92, "category" => "Prof", "name" => "Accounts", "created_at" => $now, "updated_at" => $now],
            ["code" => 4, "category" => "Prof", "name" => "Agricultural", "created_at" => $now, "updated_at" => $now],
            ["code" => 255, "category" => "Prof", "name" => "Animal Welfare Organization", "created_at" => $now, "updated_at" => $now],
            ["code" => 110, "category" => "Prof", "name" => "Applied studies", "created_at" => $now, "updated_at" => $now],
            ["code" => 240, "category" => "Prof", "name" => "Business & Professional Organizations", "created_at" => $now, "updated_at" => $now],
            ["code" => 250, "category" => "Prof", "name" => "Business Aviation Association", "created_at" => $now, "updated_at" => $now],
            ["code" => 260, "category" => "Prof", "name" => "Business Council", "created_at" => $now, "updated_at" => $now],
            ["code" => 265, "category" => "Prof", "name" => "Businessmen Forum", "created_at" => $now, "updated_at" => $now],
            ["code" => 166, "category" => "Prof", "name" => "Car registration & transfer services", "created_at" => $now, "updated_at" => $now],
            ["code" => 295, "category" => "Prof", "name" => "Charity Market", "created_at" => $now, "updated_at" => $now],
            ["code" => 290, "category" => "Prof", "name" => "Charity Society", "created_at" => $now, "updated_at" => $now],
            ["code" => 212, "category" => "Prof", "name" => "Cleaning services", "created_at" => $now, "updated_at" => $now],
            ["code" => 42, "category" => "Prof", "name" => "Combing and upholstery", "created_at" => $now, "updated_at" => $now],
            ["code" => 315, "category" => "Prof", "name" => "Commercial Library", "created_at" => $now, "updated_at" => $now],
            ["code" => 2, "category" => "Prof", "name" => "Consultancy -A- Agriculture and Soil", "created_at" => $now, "updated_at" => $now],
            ["code" => 3, "category" => "Prof", "name" => "Consultancy -B- Engineering", "created_at" => $now, "updated_at" => $now],
            ["code" => 5, "category" => "Prof", "name" => "Consultancy -C- Petrol and Water", "created_at" => $now, "updated_at" => $now],
            ["code" => 6, "category" => "Prof", "name" => "Consultancy -D- management, information and marketing", "created_at" => $now, "updated_at" => $now],
            ["code" => 214, "category" => "Prof", "name" => "documents destroying & storage", "created_at" => $now, "updated_at" => $now],
            ["code" => 80, "category" => "Prof", "name" => "Education", "created_at" => $now, "updated_at" => $now],
            ["code" => 75, "category" => "Prof", "name" => "Event organizers", "created_at" => $now, "updated_at" => $now],
            ["code" => 88, "category" => "Prof", "name" => "Exhibition organizers", "created_at" => $now, "updated_at" => $now],
            ["code" => 223, "category" => "Prof", "name" => "Facilities Management Group", "created_at" => $now, "updated_at" => $now],
            ["code" => 211, "category" => "Prof", "name" => "finance consultants", "created_at" => $now, "updated_at" => $now],
            ["code" => 9, "category" => "Prof", "name" => "Fishing and fish farming", "created_at" => $now, "updated_at" => $now],
            ["code" => 130, "category" => "Prof", "name" => "Fishing cages & net manufacturing", "created_at" => $now, "updated_at" => $now],
            ["code" => 84, "category" => "Prof", "name" => "Gents salon", "created_at" => $now, "updated_at" => $now],
            ["code" => 38, "category" => "Prof", "name" => "Gents tailoring and design", "created_at" => $now, "updated_at" => $now],
            ["code" => 138, "category" => "Prof", "name" => "Government liaison office", "created_at" => $now, "updated_at" => $now],
            ["code" => 111, "category" => "Prof", "name" => "Halls and exhibition", "created_at" => $now, "updated_at" => $now],
            ["code" => 39, "category" => "Prof", "name" => "Handicraft workshops", "created_at" => $now, "updated_at" => $now],
            ["code" => 216, "category" => "Prof", "name" => "hospitals & recovery houses", "created_at" => $now, "updated_at" => $now],
            ["code" => 82, "category" => "Prof", "name" => "Institutes and education", "created_at" => $now, "updated_at" => $now],
            ["code" => 210, "category" => "Prof", "name" => "insurance consultants", "created_at" => $now, "updated_at" => $now],
            ["code" => 218, "category" => "Prof", "name" => "key duplicators & stamp making", "created_at" => $now, "updated_at" => $now],
            ["code" => 85, "category" => "Prof", "name" => "Kids Salon", "created_at" => $now, "updated_at" => $now],
            ["code" => 94, "category" => "Prof", "name" => "Laboratories", "created_at" => $now, "updated_at" => $now],
            ["code" => 169, "category" => "Prof", "name" => "Labour Supply & employment agency", "created_at" => $now, "updated_at" => $now],
            ["code" => 83, "category" => "Prof", "name" => "Ladies salon", "created_at" => $now, "updated_at" => $now],
            ["code" => 37, "category" => "Prof", "name" => "Ladies tailoring and design", "created_at" => $now, "updated_at" => $now],
            ["code" => 87, "category" => "Prof", "name" => "Laundry", "created_at" => $now, "updated_at" => $now],
            ["code" => 93, "category" => "Prof", "name" => "Legal services", "created_at" => $now, "updated_at" => $now],
            ["code" => 1, "category" => "Prof", "name" => "Livestock Farming", "created_at" => $now, "updated_at" => $now],
            ["code" => 152, "category" => "Prof", "name" => "Medical Clinic", "created_at" => $now, "updated_at" => $now],
            ["code" => 217, "category" => "Prof", "name" => "medical laboratories", "created_at" => $now, "updated_at" => $now],
            ["code" => 215, "category" => "Prof", "name" => "motor & motorcycles driving institutes", "created_at" => $now, "updated_at" => $now],
            ["code" => 44, "category" => "Prof", "name" => "Motor vehicle repairing", "created_at" => $now, "updated_at" => $now],
            ["code" => 300, "category" => "Prof", "name" => "Not Grouped", "created_at" => $now, "updated_at" => $now],
            ["code" => 81, "category" => "Prof", "name" => "Nursery", "created_at" => $now, "updated_at" => $now],
            ["code" => 245, "category" => "Prof", "name" => "Office Of International Organization", "created_at" => $now, "updated_at" => $now],
            ["code" => 168, "category" => "Prof", "name" => "Other engineering services", "created_at" => $now, "updated_at" => $now],
            ["code" => 219, "category" => "Prof", "name" => "outlet group", "created_at" => $now, "updated_at" => $now],
            ["code" => 208, "category" => "Prof", "name" => "personal requisites repairing", "created_at" => $now, "updated_at" => $now],
            ["code" => 18, "category" => "Prof", "name" => "Printing and publishing services", "created_at" => $now, "updated_at" => $now],
            ["code" => 86, "category" => "Prof", "name" => "Recreation halls", "created_at" => $now, "updated_at" => $now],
            ["code" => 141, "category" => "Prof", "name" => "Regional liaison office", "created_at" => $now, "updated_at" => $now],
            ["code" => 45, "category" => "Prof", "name" => "Repairing of electrical & electronic appliances", "created_at" => $now, "updated_at" => $now],
            ["code" => 46, "category" => "Prof", "name" => "Repairing of equipments", "created_at" => $now, "updated_at" => $now],
            ["code" => 139, "category" => "Prof", "name" => "Representative office", "created_at" => $now, "updated_at" => $now],
            ["code" => 47, "category" => "Prof", "name" => "Restaurants and coffee shops", "created_at" => $now, "updated_at" => $now],
            ["code" => 202, "category" => "Prof", "name" => "Separate professional activities", "created_at" => $now, "updated_at" => $now],
            ["code" => 99, "category" => "Prof", "name" => "Sewage and cleaning services", "created_at" => $now, "updated_at" => $now],
            ["code" => 270, "category" => "Prof", "name" => "Social Club", "created_at" => $now, "updated_at" => $now],
            ["code" => 285, "category" => "Prof", "name" => "Social Work Activities", "created_at" => $now, "updated_at" => $now],
            ["code" => 172, "category" => "Prof", "name" => "Special purpose Firm", "created_at" => $now, "updated_at" => $now],
            ["code" => 151, "category" => "Prof", "name" => "Sport Club", "created_at" => $now, "updated_at" => $now],
            ["code" => 222, "category" => "Prof", "name" => "studio - professional license", "created_at" => $now, "updated_at" => $now],
            ["code" => 101, "category" => "Prof", "name" => "studio - trade license", "created_at" => $now, "updated_at" => $now],
            ["code" => 203, "category" => "Prof", "name" => "technical & professional workshops", "created_at" => $now, "updated_at" => $now],
            ["code" => 213, "category" => "Prof", "name" => "translation group", "created_at" => $now, "updated_at" => $now],
            ["code" => 100, "category" => "Prof", "name" => "Typing and translation", "created_at" => $now, "updated_at" => $now],
            ["code" => 153, "category" => "Prof", "name" => "Veterinary clinic", "created_at" => $now, "updated_at" => $now],
            ["code" => 275, "category" => "Prof", "name" => "Women Club", "created_at" => $now, "updated_at" => $now],
            ["code" => 501, "category" => "Tour", "name" => "Tourism Activities", "created_at" => $now, "updated_at" => $now]
        ];

        DB::table('activity_types')->insert($activities);
    }
}